### ISSUE TITLE
Installation help !

### ISSUE THREAD

**Issue by Sizzlarr** [PaesslerAG/JMXMiniProbe#3]
Hi team,

Can you help me to install this Probe please ?

I've just downloaded from GIT the repo and create the prtgjmx.properties

So when i try to launch the script i got this error ( but i'm beginner with Java )

[root@tbxpp JMXMiniProbe-master]# ./JMXMiniProbe.sh
Exception in thread "main" java.lang.NoClassDefFoundError: com/paessler/prtg/jmx/DaemonMain
Caused by: java.lang.ClassNotFoundException: com.paessler.prtg.jmx.DaemonMain
        at java.net.URLClassLoader$1.run(URLClassLoader.java:200)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:188)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:307)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:252)
        at java.lang.ClassLoader.loadClassInternal(ClassLoader.java:320)
Could not find the main class: com.paessler.prtg.jmx.DaemonMain.  Program will exit.

Thanks,
Adrien

**Comment by Sizzlarr** [comment]
[root@tbxpp JMXMiniProbe-master]# env
PATH=/usr/local/java/jdk1.8.0_31/bin:/usr/sbin:/usr/kerberos/sbin:/usr/kerberos/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin
PWD=/root/JMX/JMXMiniProbe-master
JAVA_HOME=/usr/local/java/jdk1.8.0_31
CLASSPATH=/usr/local/java/jdk1.8.0_31/lib
[root@tbxpp JMXMiniProbe-master]# ./JMXMiniProbe.sh
Error: Could not find or load main class com.paessler.prtg.jmx.DaemonMain

**Comment by JRAndreassen** [comment]
Did you figure it out ?
It all looks like class path problems.
When you unzip the JAR file, it should create the (non-standard) path WEB-INF/.... as used by App servers. This path is used bu the shell script to resolve libs.
there are also executables for use with JSW. Though not tested, these can be downloaded from (http://wrapper.tanukisoftware.org).

**Comment by NobleMajo** [comment]
hi,
are there any new infos or tips about the class load problem?

I tried the with the release JMXProbe.war and the JMXMiniProbe.sh script and got the same issue.

Error: Could not find or load main class com.paessler.prtg.jmx.DaemonMain
Caused by: java.lang.ClassNotFoundException: com.paessler.prtg.jmx.DaemonMain

**Comment by NobleMajo** [comment]
The problem is addressed in the linked answer by a Paessler supporter:
https://kb.paessler.com/en/topic/61010-how-can-i-monitor-java-applications-via-jmx-with-a-prtg-mini-probe#reply-254253

1. Download the `.zip` or `.tar.gz` and `.war` files from the github releases.
2. Unzip the archive and place the .war file in the extracted folder.
3. Jump into the extracted folder and unzip the war file: `jar -xvf <WarFile.war>`.
4. Jump into the `bin` folder and run the required startup script (*nix = `runJMXMiniProbe`).
5. Use the option `-c` to define the `prtgjmx.properties` path.

After the issue I had further problems which were answered in the linked forum article.
Unfortunately, parts of the README are not detailed or even misleading.
After a lot of frustration it finally worked to connect to my PRTG instance as Mini Probe.
